ALTER TABLE "PromoCode"
    ADD COLUMN IF NOT EXISTS "codeType" TEXT NOT NULL DEFAULT 'STANDARD',
    ADD COLUMN IF NOT EXISTS "campaignName" TEXT,
    ADD COLUMN IF NOT EXISTS "influencerName" TEXT;
